import { writeVfsToDirectory } from "make-vfs"
import { DatabaseTree } from "../types"
import { getVfsFromTree } from "./get-vfs-from-database-tree"

export const writeDatabaseTreeToDirectory = async (
  db: DatabaseTree,
  outDir: string,
  { header = "Generated by pg-schema-dump" } = {}
) => {
  const vfs = getVfsFromTree(db)
  await writeVfsToDirectory({
    vfs,
    outDir,
  })
}

export default writeDatabaseTreeToDirectory
